
spring:
  datasource:
    url: jdbc:mysql://10.128.0.4:3306/test?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001
